services:
  app:
    container_name: Odin-Valley
    build:
      context: .                   # Mantém a raiz como base para enxergar o index.py
      dockerfile: docker/Dockerfile # Indica o caminho do arquivo de receita
    privileged: true # Dá permissão total ao hardware (som/vídeo)
    volumes:
      - .:/usr/src/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=/tmp
      - PYGAME_DETECT_AVX2=1
      # Força o uso do driver de vídeo do sistema
      - SDL_VIDEODRIVER=x11
    devices:
      - /dev/dri:/dev/dri
      - /dev/snd:/dev/snd
    network_mode: host
    stdin_open: true
    tty: true
    command: python index.py