services:
  app:
    container_name: Odin-Valley
    build:
      context: .
      dockerfile: docker/Dockerfile
    privileged: true
    volumes:
      - .:/usr/src/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      # INCREMENTO: Mapeia o socket de áudio do seu usuário real
      - /run/user/1000/pulse:/run/user/1000/pulse
      - ~/.config/pulse/cookie:/root/.config/pulse/cookie
    environment:
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=/tmp
      - PYGAME_DETECT_AVX2=1
      - SDL_VIDEODRIVER=x11
      # INCREMENTO: Aponta o servidor de som para o socket mapeado
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
    devices:
      - /dev/dri:/dev/dri
      - /dev/snd:/dev/snd
    group_add:
      - audio
      - video
    network_mode: host
    stdin_open: true
    tty: true
    command: python index.py