services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      # Resolve o erro de XDG
      - XDG_RUNTIME_DIR=/tmp
      # Otimização que o log sugeriu
      - PYGAME_DETECT_AVX2=1
    # Dá acesso ao hardware de som e vídeo
    devices:
      - /dev/dri:/dev/dri
      - /dev/snd:/dev/snd
    network_mode: host
    stdin_open: true
    tty: true
    command: python index.py