FROM python:3

# Mantemos as bibliotecas do SDL que o Pygame exige para funcionar
RUN apt-get update && apt-get install -y \
    libsdl2-dev \
    libsdl2-image-dev \
    libsdl2-mixer-dev \
    libsdl2-ttf-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY docker/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Comando simples para rodar o script do jogo
CMD ["python", "index.py"]